CREATE TABLE [dbo].[BOLETA]
(
[NUMBOL] [varchar] (50) COLLATE Modern_Spanish_CI_AS NOT NULL,
[FECHA] [date] NOT NULL,
[CODHCLIN] [varchar] (50) COLLATE Modern_Spanish_CI_AS NOT NULL,
[CODDBOL] [int] NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[BOLETA] ADD CONSTRAINT [PK__BOLETA__7542EC3DCDB59CF1] PRIMARY KEY CLUSTERED  ([NUMBOL]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[BOLETA] ADD CONSTRAINT [FK_BOLETA_DETALLEBOLETA] FOREIGN KEY ([CODDBOL]) REFERENCES [dbo].[DETALLEBOLETA] ([CODDBOL])
GO
ALTER TABLE [dbo].[BOLETA] ADD CONSTRAINT [FK_BOLETA_HISTORIACLINICA] FOREIGN KEY ([CODHCLIN]) REFERENCES [dbo].[HISTORIACLINICA] ([CODHCLIN])
GO
