CREATE TABLE [dbo].[PRODUCTO]
(
[CODPROD] [varchar] (50) COLLATE Modern_Spanish_CI_AS NOT NULL,
[NOMPROD] [varchar] (100) COLLATE Modern_Spanish_CI_AS NOT NULL,
[PRECOMP] [money] NOT NULL,
[PREVENT] [money] NOT NULL,
[CANT] [numeric] (18, 0) NOT NULL,
[FECCADU] [date] NOT NULL,
[CODTPROD] [char] (1) COLLATE Modern_Spanish_CI_AS NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[PRODUCTO] ADD CONSTRAINT [PK__PRODUCTO__73339083C8321899] PRIMARY KEY CLUSTERED  ([CODPROD]) ON [PRIMARY]
GO
