CREATE TABLE [dbo].[DETALLESERVICIO]
(
[CODDSERV] [int] NOT NULL,
[CODPER] [varchar] (50) COLLATE Modern_Spanish_CI_AS NOT NULL,
[CODSERV] [varchar] (50) COLLATE Modern_Spanish_CI_AS NOT NULL,
[DISPON] [char] (1) COLLATE Modern_Spanish_CI_AS NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[DETALLESERVICIO] ADD CONSTRAINT [PK__DETALLES__0C3E9D77D295212A] PRIMARY KEY CLUSTERED  ([CODDSERV]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[DETALLESERVICIO] ADD CONSTRAINT [FK_DETALLESERVICIO_TIPOSERVICIO] FOREIGN KEY ([CODSERV]) REFERENCES [dbo].[TIPOSERVICIO] ([CODSERV])
GO
