CREATE TABLE [dbo].[DETALLESERVICIO]
(
[IDSERV] [int] NOT NULL IDENTITY(1, 1),
[IDPER] [int] NOT NULL,
[DISPSERV] [char] (1) COLLATE Modern_Spanish_CI_AS NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[DETALLESERVICIO] ADD CONSTRAINT [PK__DETALLES__82A3FA97846543F9] PRIMARY KEY CLUSTERED  ([IDSERV]) ON [PRIMARY]
GO
