CREATE TABLE [dbo].[DETALLEHISTORIACLINICA]
(
[IDDCLIN] [int] NOT NULL IDENTITY(1, 1),
[IDHCLIN] [int] NOT NULL,
[FECHTRATCLIN] [date] NOT NULL,
[IDSERV] [int] NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[DETALLEHISTORIACLINICA] ADD CONSTRAINT [PK__DETALLEH__635C8C657EA2D80F] PRIMARY KEY CLUSTERED  ([IDDCLIN]) ON [PRIMARY]
GO
