CREATE TABLE [dbo].[DETALLEHISTORIACLINICA]
(
[CODDCLIN] [int] NOT NULL,
[FECHTRAT] [date] NOT NULL,
[CODSERV] [varchar] (50) COLLATE Modern_Spanish_CI_AS NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[DETALLEHISTORIACLINICA] ADD CONSTRAINT [PK__DETALLEH__9361A51EA0005190] PRIMARY KEY CLUSTERED  ([CODDCLIN]) ON [PRIMARY]
GO
