CREATE TABLE [dbo].[MASCOTA]
(
[IDMAS] [int] NOT NULL IDENTITY(1, 1),
[NOMMAS] [varchar] (25) COLLATE Modern_Spanish_CI_AS NOT NULL,
[FECNACMAS] [date] NOT NULL,
[TIPMAS] [varchar] (50) COLLATE Modern_Spanish_CI_AS NOT NULL,
[RAZMAS] [varchar] (50) COLLATE Modern_Spanish_CI_AS NOT NULL,
[PESMAS] [numeric] (18, 0) NOT NULL,
[IDPER] [int] NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[MASCOTA] ADD CONSTRAINT [PK__MASCOTA__94185D2E28C46883] PRIMARY KEY CLUSTERED  ([IDMAS]) ON [PRIMARY]
GO
