CREATE TABLE [dbo].[HISTORIACLINICA]
(
[CODHCLIN] [varchar] (50) COLLATE Modern_Spanish_CI_AS NOT NULL,
[CODMASC] [varchar] (50) COLLATE Modern_Spanish_CI_AS NOT NULL,
[EST] [char] (1) COLLATE Modern_Spanish_CI_AS NULL,
[FECAPER] [date] NULL,
[CODDCLIN] [int] NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[HISTORIACLINICA] ADD CONSTRAINT [PK__HISTORIA__FCB587B13F5036BD] PRIMARY KEY CLUSTERED  ([CODHCLIN]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[HISTORIACLINICA] ADD CONSTRAINT [FK_HISTORIACLINICA_DETALLEHISTORIACLINICA] FOREIGN KEY ([CODDCLIN]) REFERENCES [dbo].[DETALLEHISTORIACLINICA] ([CODDCLIN])
GO
ALTER TABLE [dbo].[HISTORIACLINICA] ADD CONSTRAINT [FK_HISTORIACLINICA_MASCOTA] FOREIGN KEY ([CODMASC]) REFERENCES [dbo].[MASCOTA] ([CODMASC])
GO
