CREATE TABLE [dbo].[PRODUCTO]
(
[IDPROD] [int] NOT NULL IDENTITY(1, 1),
[NOMPROD] [varchar] (100) COLLATE Modern_Spanish_CI_AS NOT NULL,
[PRECOMPPROD] [money] NOT NULL,
[PREVENTPROD] [money] NOT NULL,
[CANTPROD] [numeric] (18, 0) NOT NULL,
[FCADPROD] [date] NOT NULL,
[TIPPRO] [char] (1) COLLATE Modern_Spanish_CI_AS NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[PRODUCTO] ADD CONSTRAINT [PK__PRODUCTO__8E0A903948824509] PRIMARY KEY CLUSTERED  ([IDPROD]) ON [PRIMARY]
GO
