CREATE TABLE [dbo].[HISTORIACLINICA]
(
[IDHCLIN] [int] NOT NULL IDENTITY(1, 1),
[IDMAS] [int] NOT NULL,
[ESTCLIN] [char] (1) COLLATE Modern_Spanish_CI_AS NULL,
[FECAPERCLIN] [date] NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[HISTORIACLINICA] ADD CONSTRAINT [PK__HISTORIA__1404C91C4A9D4D40] PRIMARY KEY CLUSTERED  ([IDHCLIN]) ON [PRIMARY]
GO
