CREATE TABLE [dbo].[PERSONA]
(
[IDPER] [int] NOT NULL IDENTITY(1, 1),
[NOMPER] [varchar] (50) COLLATE Modern_Spanish_CI_AS NOT NULL,
[APEPER] [varchar] (100) COLLATE Modern_Spanish_CI_AS NOT NULL,
[DIRPER] [varchar] (150) COLLATE Modern_Spanish_CI_AS NOT NULL,
[DNIPER] [numeric] (18, 0) NOT NULL,
[TELPER] [numeric] (18, 0) NOT NULL,
[EMAPER] [varchar] (150) COLLATE Modern_Spanish_CI_AS NOT NULL,
[TIPPER] [char] (1) COLLATE Modern_Spanish_CI_AS NULL,
[ESTPER] [char] (1) COLLATE Modern_Spanish_CI_AS NOT NULL CONSTRAINT [DF_PERSONA_ESTPER] DEFAULT ('A')
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[PERSONA] ADD CONSTRAINT [PK__PERSONA__98FE8B7E515C939A] PRIMARY KEY CLUSTERED  ([IDPER]) ON [PRIMARY]
GO
