CREATE TABLE [dbo].[MEDICINA]
(
[CODMED] [varchar] (50) COLLATE Modern_Spanish_CI_AS NOT NULL,
[NOMMED] [varchar] (100) COLLATE Modern_Spanish_CI_AS NOT NULL,
[PREC] [money] NOT NULL,
[DOSIS] [varchar] (250) COLLATE Modern_Spanish_CI_AS NOT NULL,
[FECPRO] [date] NOT NULL,
[FECVEN] [date] NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[MEDICINA] ADD CONSTRAINT [PK__MEDICINA__B1EE0B06DC07B9B1] PRIMARY KEY CLUSTERED  ([CODMED]) ON [PRIMARY]
GO
