CREATE TABLE [dbo].[DETALLEBOLETA]
(
[CODDBOL] [int] NOT NULL,
[CODMED] [varchar] (50) COLLATE Modern_Spanish_CI_AS NOT NULL,
[CODPROD] [varchar] (50) COLLATE Modern_Spanish_CI_AS NOT NULL,
[CODSERV] [varchar] (50) COLLATE Modern_Spanish_CI_AS NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[DETALLEBOLETA] ADD CONSTRAINT [PK__DETALLEB__EF6940B70D02B1C8] PRIMARY KEY CLUSTERED  ([CODDBOL]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[DETALLEBOLETA] ADD CONSTRAINT [FK_DETALLEBOLETA_MEDICINA] FOREIGN KEY ([CODMED]) REFERENCES [dbo].[MEDICINA] ([CODMED])
GO
ALTER TABLE [dbo].[DETALLEBOLETA] ADD CONSTRAINT [FK_DETALLEBOLETA_PRODUCTO] FOREIGN KEY ([CODPROD]) REFERENCES [dbo].[PRODUCTO] ([CODPROD])
GO
ALTER TABLE [dbo].[DETALLEBOLETA] ADD CONSTRAINT [FK_DETALLEBOLETA_TIPOSERVICIO] FOREIGN KEY ([CODSERV]) REFERENCES [dbo].[TIPOSERVICIO] ([CODSERV])
GO
