CREATE TABLE [dbo].[MASCOTA]
(
[CODMASC] [varchar] (50) COLLATE Modern_Spanish_CI_AS NOT NULL,
[NOMMASC] [varchar] (25) COLLATE Modern_Spanish_CI_AS NOT NULL,
[FECNAC] [date] NOT NULL,
[TIPMASC] [varchar] (50) COLLATE Modern_Spanish_CI_AS NOT NULL,
[RAZA] [varchar] (50) COLLATE Modern_Spanish_CI_AS NOT NULL,
[PESO] [numeric] (18, 0) NOT NULL,
[CODPER] [varchar] (50) COLLATE Modern_Spanish_CI_AS NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[MASCOTA] ADD CONSTRAINT [PK__MASCOTA__504073BFA93F0517] PRIMARY KEY CLUSTERED  ([CODMASC]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[MASCOTA] ADD CONSTRAINT [FK_MASCOTA_PERSONA] FOREIGN KEY ([CODPER]) REFERENCES [dbo].[PERSONA] ([CODPER])
GO
