CREATE TABLE [dbo].[TIPOSERVICIO]
(
[CODSERV] [varchar] (50) COLLATE Modern_Spanish_CI_AS NOT NULL,
[NOMSERV] [varchar] (100) COLLATE Modern_Spanish_CI_AS NOT NULL,
[DESCRIP] [varchar] (150) COLLATE Modern_Spanish_CI_AS NOT NULL,
[COSTSERV] [money] NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[TIPOSERVICIO] ADD CONSTRAINT [PK__TIPOSERV__759FB7D65E7EFE77] PRIMARY KEY CLUSTERED  ([CODSERV]) ON [PRIMARY]
GO
