CREATE TABLE [dbo].[MEDICINA]
(
[IDMED] [int] NOT NULL IDENTITY(1, 1),
[NOMMED] [varchar] (100) COLLATE Modern_Spanish_CI_AS NOT NULL,
[PRECMED] [money] NOT NULL,
[DOSMED] [varchar] (250) COLLATE Modern_Spanish_CI_AS NOT NULL,
[FECPROMED] [date] NOT NULL,
[FECVENMED] [date] NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[MEDICINA] ADD CONSTRAINT [PK__MEDICINA__941979DCB20C29FE] PRIMARY KEY CLUSTERED  ([IDMED]) ON [PRIMARY]
GO
