CREATE TABLE [dbo].[USUARIOS]
(
[CODUSUA] [int] NOT NULL,
[USUA] [varchar] (50) COLLATE Modern_Spanish_CI_AS NOT NULL,
[CONTRA] [varchar] (50) COLLATE Modern_Spanish_CI_AS NOT NULL,
[CODPER] [varchar] (50) COLLATE Modern_Spanish_CI_AS NOT NULL,
[CODNIV] [char] (1) COLLATE Modern_Spanish_CI_AS NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[USUARIOS] ADD CONSTRAINT [PK__USUARIOS__FE616F7479E4C92A] PRIMARY KEY CLUSTERED  ([CODUSUA]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[USUARIOS] ADD CONSTRAINT [FK_USUARIOS_PERSONA] FOREIGN KEY ([CODPER]) REFERENCES [dbo].[PERSONA] ([CODPER])
GO
