CREATE TABLE [dbo].[SERVICIO]
(
[IDSERV] [int] NOT NULL IDENTITY(1, 1),
[NOMSERV] [varchar] (100) COLLATE Modern_Spanish_CI_AS NOT NULL,
[DESCRSERV] [varchar] (150) COLLATE Modern_Spanish_CI_AS NOT NULL,
[COSTSERV] [money] NOT NULL,
[IDDETSERV] [int] NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[SERVICIO] ADD CONSTRAINT [PK__SERVICIO__82A3FA9714963FC7] PRIMARY KEY CLUSTERED  ([IDSERV]) ON [PRIMARY]
GO
